spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url:  jdbc:oracle:thin:@kys_high?TNS_ADMIN=./src/main/resources/Wallet_kys
    username: admin
    password: dbsQkd12!#or
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none